### PR TITLE
Status item image with animation

### PR DESCRIPTION
**Pull request by ricobeck**
Added an example image with animation during syncing

### CODE REVIEW

**Comment by odrobnik** [comment]
@ricobeck should this be animating? I don't see an animation... Please update your master and check.

**Comment by odrobnik** [comment]
@ricobeck Ah, never mind. Now I see it.

**Comment by odrobnik** [comment]
@ricobeck I just fixed a problem where the completion block would overtake the download operations. Please be sure to pull your code.

Also please do your changes in branches in the main project. Since I made you a contributor your don't need to fork it.

**Comment by ricobeck** [comment]
i did this before you added me. from now on i'll use the main project.

**Comment by odrobnik** [comment]
Great, looking forward to additional stuff. How about changing the Sync Now to a Cancel Sync button?

**Comment by ricobeck** [comment]
this is what will do next. i'll use a development branch so you can check my changes and merge them into master.

**Comment by odrobnik** [comment]
Actually when this has progressed a little further I want to do development on a "develop" branch and have the merges go into this. Then whenever we merge into master we tag this and this would be released with developer id and sparkle for everybody to enjoy.

**Comment by ricobeck** [comment]
i am used to git flow so i'll use feature branches. is this okay for you?

**Comment by odrobnik** [comment]
Yes, I'd like your leadership on this so that I can learn proper branching strategy myself

**Comment by fcy** [comment]
About the git flow. I like to name features branches like this: `<username-working-on-it>/<feature-description>`, e.g.: `fcy/auto-organize-reports`

Is this good? Do you like it?

**Comment by odrobnik** [comment]
good suggestion, but I don't like to have to type the whole username, just a short prefix identifying oneself is sufficient. You can have slashes in the branch name? I was using od_feature before fearing that slashes might be a problem...

**Comment by fcy** [comment]
Yes you can. Some clients even use the slashes to organize the branches in a tree view.

**Comment by odrobnik** [comment]
Slashes it is.

**Pull request merged**
