### PR TITLE
Menu improvements

### PR DESCRIPTION
**Pull request by JanX2**

### CODE REVIEW

**Comment by odrobnik** [comment]
@JanX2 Can you please add some description to pull requests so that the person merging them can form a quick idea of what this is about?

**Comment by JanX2** [comment]
Do you consider the commit messages insufficient?

**Comment by odrobnik** [comment]
Commit messages describe individual commits. Pull messages describe the overall idea of the Set of changes

**Comment by JanX2** [comment]
Sure. But there are only two commits in this one. :) You are absolutely right in the general case, though.

**Pull request merged**
